# Generated by Django 2.2.16 on 2021-10-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211021_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='', verbose_name='Описание пользователя'),
        ),
    ]
