# Generated by Django 2.2.16 on 2021-10-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211021_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('anonymous', 'Анонимный'), ('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', error_messages={'max_length': 'Превышена длинна роли пользователя'}, max_length=16, verbose_name='Тип пользователя'),
        ),
    ]
