# Generated by Django 2.2.16 on 2021-10-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_title_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('name',), 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
