# Generated by Django 2.2.16 on 2021-10-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20211020_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catergory',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
