# Generated by Django 2.2.16 on 2021-10-21 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20211020_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, error_messages={'MaxValueValidator': 'Треки не должны быть из будущего', 'MinValueValidator': 'Записи должны быть не старше 19-го века'}, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2021)], verbose_name='Год Выпуска'),
        ),
    ]
