# Generated by Django 2.2.16 on 2021-10-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20211023_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, error_messages={'MaxValueValidator': 'Треки не должны быть из будущего', 'MinValueValidator': 'Записи не должны быть старше 19 века'}, verbose_name='Год Выпуска'),
        ),
    ]
